name: Triggered Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Print Payload
        run: echo "Triggered by repository: ${{ github.event.client_payload.repo }}"
