name: BBBBBBB Repo

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write
  repository-projects: write
jobs:
  execute-bpmn:
    runs-on: ubuntu-latest

    steps:
      - id: Checkout
        name: Checkout
        uses: actions/checkout@v4
  
      - id: Setup_JDK_21
        name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Execute BPMN
        run: |
          wget https://downloads.camunda.cloud/release/camunda-bpm/run/7.21/camunda-bpm-run-7.21.0.zip
          unzip camunda-bpm-run-7.21.0.zip -d camunda-bpm-run
          cd camunda-bpm-run

          cp ../process.bpmn ./configuration/resources/

          ./start.sh 
          sleep 30
          
          response=$(curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"variables":{}}' \
            http://localhost:8080/engine-rest/process-definition/key/process_a/start)

          echo "Response from curl request process: $response"

          rs=$(curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/msob-test/repo_b/dispatches \
            -d '{"event_type":"trigger-action-b"}')
          
          echo "Response from curl request: $rs"
        env:
          GITHUB_TOKEN: ${{ secrets.TTT }}
