name: Execute BPMN

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Print Payload
        run: echo "Triggered by repository: ${{ github.event.client_payload.repo }}"
